apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: tce-workshops
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: tce-dev-guide
    capacity: 3
    expires: 60m
    orphaned: 5m
